#!/usr/bin/env bash
# Idempotent Cloud Agent install script for the TDLS storefront.
# Prepares: local PostgreSQL (app + strapi DBs), .env with dev defaults,
# node_modules (which also generates the Prisma clients via postinstall),
# the app database schema, and a seeded superadmin.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PG_VERSION=16
PG_CLUSTER=main
DB_USER=tdls
DB_PASS=tdls
APP_DB=app_db_dev
STRAPI_DB=strapi_db

log() { printf '\n[install] %s\n' "$*"; }

# 1) Ensure PostgreSQL is installed (skipped when the base snapshot already has it).
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  log "Installing PostgreSQL ${PG_VERSION}..."
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
fi

# 2) Ensure the cluster is online (db push / seed below need it).
#    Key off real readiness so a stale postmaster.pid (from a snapshot that
#    captured a running cluster) is cleared by pg_ctlcluster on start.
if ! sudo -u postgres pg_isready -q 2>/dev/null; then
  log "Starting PostgreSQL cluster ${PG_VERSION}/${PG_CLUSTER}..."
  sudo pg_ctlcluster "$PG_VERSION" "$PG_CLUSTER" start || true
fi

# Wait for readiness.
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q 2>/dev/null; then break; fi
  sleep 1
done

# 3) Ensure role, databases and required extensions exist (idempotent).
log "Ensuring database role and databases..."
sudo -u postgres psql -v ON_ERROR_STOP=1 -q <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='${DB_USER}') THEN
    CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASS}' SUPERUSER;
  END IF;
END \$\$;
SQL
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='${APP_DB}'" | grep -q 1 \
  || sudo -u postgres createdb -O "$DB_USER" "$APP_DB"
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='${STRAPI_DB}'" | grep -q 1 \
  || sudo -u postgres createdb -O "$DB_USER" "$STRAPI_DB"
for db in "$APP_DB" "$STRAPI_DB"; do
  sudo -u postgres psql -d "$db" -q -c 'CREATE EXTENSION IF NOT EXISTS citext;' \
    -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm;' \
    -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
done

# 4) Generate a local .env with dev defaults if one does not already exist.
# Real secrets are never committed; this file is git-ignored and only holds
# local development values pointing at the local PostgreSQL instance.
if [ ! -f .env ]; then
  log "Writing local .env (dev defaults)..."
  APP_URL="postgresql://${DB_USER}:${DB_PASS}@127.0.0.1:5432/${APP_DB}"
  STRAPI_URL_DB="postgresql://${DB_USER}:${DB_PASS}@127.0.0.1:5432/${STRAPI_DB}"
  SECRET_A="$(openssl rand -hex 32)"
  SECRET_ADMIN="$(openssl rand -hex 32)"
  SECRET_OTP="$(openssl rand -hex 32)"
  cat > .env <<EOF
# ---- Local dev environment (generated by .cursor/install.sh; not committed) ----
NODE_ENV=development

# App database (Prisma app schema)
APP_DB_USER_POOLER_CB=${APP_URL}
APP_DB_OWNER_DIRECT=${APP_URL}
APP_DB_USER_DIRECT=${APP_URL}
DATABASE_URL=${APP_URL}
DIRECT_URL=${APP_URL}

# Strapi (CMS) read-only DB used by the Prisma strapi client
STRAPI_DATABASE_URL_RO=${STRAPI_URL_DB}

# Strapi CMS HTTP endpoint (not run locally; storefront degrades gracefully)
NEXT_PUBLIC_STRAPI_URL=http://127.0.0.1:1337
STRAPI_URL=http://127.0.0.1:1337

# Site / auth
NEXT_PUBLIC_SITE_URL=http://localhost:3000
NEXTAUTH_URL=http://localhost:3000
AUTH_URL=http://localhost:3000
AUTH_TRUST_HOST=true
AUTH_SECRET=${SECRET_A}
NEXTAUTH_SECRET=${SECRET_A}
CUSTOMER_AUTH_SECRET=${SECRET_A}
ADMIN_AUTH_SECRET=${SECRET_ADMIN}
OTP_SECRET=${SECRET_OTP}

# Seed superadmin (used by prisma seed)
ADMIN_SEED_EMAIL=admin@tdls.local
ADMIN_SEED_PHONE=+8801700000000
ADMIN_SEED_PASSWORD=Admin12345!
ADMIN_SEED_NAME=Root Admin
EOF
fi

# 5) Install JS dependencies. postinstall generates both Prisma clients
#    (app + strapi) and copies the runtime query engines.
log "Installing npm dependencies..."
npm install --no-audit --no-fund

# 6) Sync the app schema to the database and seed the superadmin (idempotent).
log "Applying app Prisma schema (db push)..."
npx prisma db push --schema=prisma/app/schema.prisma --skip-generate

log "Seeding superadmin (idempotent)..."
npx dotenv -e .env -- node prisma/app/seed.js

# Stop the cluster cleanly so that if this install state is captured in a
# snapshot/build image it does not carry a stale postmaster.pid. start.sh
# brings PostgreSQL back up on every boot.
log "Stopping PostgreSQL cluster (clean state for snapshot)..."
sudo pg_ctlcluster "$PG_VERSION" "$PG_CLUSTER" stop || true

log "Install complete."
